#!/usr/bin/env bash

pushd ~/personal/submodules/tmux-sessionizer/
git add .
git commit -m 'automated dev commit'
git push
popd

pushd ~/personal/dev
git add .
git commit -m 'automated dev commit'
git push
popd
