# ================================================
# Moonfly theme for tmux statusbar
# Colors adapted from vim-moonfly
# GitHub: https://github.com/bluz71/vim-moonfly-colors
# ================================================

set -g @tmux-statusbar-bg "default"
set -g @tmux-statusbar-fg "#C6C6C6"
set -g @tmux-statusbar-accent "#80A0FF"
set -g @tmux-statusbar-fg-inactive "#949494"

set -g @tmux-statusbar-bg-prefix-mode "#36C692"
set -g @tmux-statusbar-fg-prefix-mode "#080808"

set -g @tmux-statusbar-selection-mode "#323437"
set -g @tmux-statusbar-cursearch "#E3C78A"

set -g @tmux-statusbar-bell-alert "#FF5D5D"
set -g @tmux-statusbar-activity-alert "#DE935F"
